wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.11
    start_time: 1683563358.903472
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.10.11
      5: 0.14.0
      8:
      - 4
      - 5
created_at:
  desc: null
  value: '2023-05-08T08:51:29'
fine_tuned_model:
  desc: null
  value: ada:ft-personal-2023-05-08-16-25-48
hyperparams:
  desc: null
  value:
    batch_size: 256
    classification_n_classes: 5
    compute_classification_metrics: true
    learning_rate_multiplier: 0.1
    n_epochs: 1
    prompt_loss_weight: 0.01
id:
  desc: null
  value: ft-tnvysbOzvkIfPgtPo6oQ3c7O
model:
  desc: null
  value: ada
n_train:
  desc: null
  value: 199891
n_valid:
  desc: null
  value: 5000
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-azQm6jrJ3FSBpJAwYcgxQxGu
result_files:
  desc: null
  value:
    bytes: 54915
    created_at: 1683563149
    filename: compiled_results.csv
    id: file-QHhhi05wgj0eBQGnpPLxXBaT
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 50313473
    created_at: 1683561086
    filename: amazon-english-full-train-sentiment-random.jsonl
    id: file-SEDigPmqhtT3QTo20ByIgpus
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1683563150
validation_files:
  desc: null
  value:
    bytes: 1267658
    created_at: 1683561088
    filename: amazon-english-full-val-sentiment-random.jsonl
    id: file-u2ik6qOwMXgDyWsTqwzELdPe
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
